version: 2.3.0.{build}
image: Visual Studio 2022
platform: Any CPU
shallow_clone: true
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
environment:
  PfxPassword:
    secure: tC3u6WA0oWdjXzbLX61Ux2tBK0KhFTT9FgUZFn0Nx0pY045twcsFBvRL+Di6SE80Nc88xaM/xloHGUAQoIq4OANLNg0BEsDYPnhziZDiLBo=
clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive
before_build:
  - cmd: dotnet --version
build_script:
- ps: >-
      $env:ARCHS = @("win-x64","win-x86","win-arm64","linux-x64")
      $env:CONFIGS = @("Release,ReleaseTrimmed")
      cd $env:APPVEYOR_BUILD_FOLDER\build\
      .\build.ps1 -ReleaseVersionNumber $env:APPVEYOR_BUILD_VERSION -Releases $env:CONFIGS -Archs $env:ARCHS -CreateArtifacts $false
test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%/src/main.test/
  - cmd: nuget install Appveyor.TestLogger -Version 2.0.0
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: dotnet test ./src/main.test/wacs.test.csproj -c Release --test-adapter-path:. --logger:Appveyor 
after_build:
- ps: >-
    cd $env:APPVEYOR_BUILD_FOLDER\build\
    .\create-artifacts.ps1 -Root $env:APPVEYOR_BUILD_FOLDER -Version $env:APPVEYOR_BUILD_VERSION -Password $env:PfxPassword -Releases $env:CONFIGS -Archs $env:ARCHS
    Get-ChildItem $env:APPVEYOR_BUILD_FOLDER\build\artifacts\ | Foreach-Object {
        Push-AppveyorArtifact $_.FullName -FileName $_.Name
    }
deploy: "off"
